apiVersion: apps/v1
kind: Deployment
metadata:
    name: test-node
    namespace: devops-tools
    labels:
        app: test-node
spec:
    replicas: 1
    minReadySeconds: 10
    selector:
        matchLabels:
            app: test-node
    template:
        metadata:
            labels:
                app: test-node
        spec:
            containers:
                - name: test-node
                  imagePullPolicy: Always
                  image: herokatodev/test-node:latest

                  ports:
                      - containerPort: 8000
